import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/context";

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Movie Sphere",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} container mx-auto`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
